### ISSUE TITLE
Request: updateOrCreatePayments

### ISSUE THREAD

**Issue by andrews05** [XeroAPI/Xero-OpenAPI#232]
We currently have a plural `createPayments` PUT action as well as a singular `createPayment` POST action.
The singular POST action doesn't really serve any purpose over the plural PUT action, so I would like to suggest replacing it with `updateOrCreatePayments`. The primary purpose of this would be to allow bulk deleting multiple payments in one call (this is not something that is shown in the Xero API docs, but it still works as expected).
It would also provide some consistency with other endpoints which use the same actions.

**Comment by SerKnight** [comment]
I'm a bit unclear on this as is. I know Xero's endpoints sometime swap the functionality for PUT and POST as to what would be expected.

Just based on docs we seem to use:

PUT Payments
> Use this method to apply payments to approved AR and AP invoices or refund AR or AP credit notes.
```
put:
      security:
        - OAuth2: [paymentservices]
      tags:
        - Accounting
      operationId: createPaymentService
```

POST Payments
> Use this method to delete (reverse) payments to invoices, credit notes, prepayments & overpayments. Note that payments created via batch payments and receipts are not supported. Payments cannot be modified, only created and deleted.
```
 post:
      security:
        - OAuth2: [accounting.transactions]
      tags:
        - Accounting
      operationId: createPayment
```

Are you proposing renaming the `POST` function to `updateOrCreatePayments`?
I think that it is a breaking change for what I'm not sure is possible. I'd have to triple check but wasn't sure if you can update existing, past the soft `delete`.
