### ISSUE TITLE
Is this properly typed for is-money vendor ext?

### ISSUE THREAD

**Issue by SerKnight** [XeroAPI/Xero-OpenAPI#259]
Hi @jenksguo - wondering if this field should be typed as is-money. Currently rolling into ruby for the money types to have proper BigDecimal format, but this seems like it should just be: type: number format: double

```yml
        Quantity:
          description: LineItem Quantity
          type: number
          format: double
          x-is-money: true
```

https://github.com/XeroAPI/Xero-OpenAPI/blob/c4158e1bfe3f417e718a6cbf9ff5cab2b62e682e/accounting-yaml/xero_accounting.yaml#L18493
