### ISSUE TITLE
ReportTitles property on ReportWithRow response should be types to an array of strings

### ISSUE THREAD

**Issue by bakenosuke** [XeroAPI/Xero-OpenAPI#6]
Right now there is not specific type declared so ends up being an array of generic objects, would be nice to have it be an array of Strings to make the response easier to work with.

see https://developer.xero.com/documentation/api/reports

**Comment by SidneyAllen** [comment]
@bakenosuke  - can you share more details around this?

- Which report are you working with?  Can you tell me which line in the spec is causing this result?

**Comment by bakenosuke** [comment]
@SidneyAllen 

Currently working with the Balance sheet and Profit and Loss reports in the accounting spec.

Here is the link to the relevant section in the spec for json and yaml:
https://github.com/XeroAPI/Xero-OpenAPI/blob/master/spec/v3/Xero_accounting_2.0.0_swagger.json#L11364
https://github.com/XeroAPI/Xero-OpenAPI/blob/master/spec/v3/Xero_accounting_2.0.0_swagger.yaml#L8944

I think it should look something like:
```yaml
  ReportTitles:
           description: Report titles array
           type: array
           items:
                     type: string
```
