### ISSUE TITLE
Date format is invalid

### ISSUE THREAD

**Issue by QuentinLemCode** [XeroAPI/Xero-OpenAPI#633]
Hello,

The date format used in Payment object is invalid : 

The OpenAPI definition defines this : 
```yml
        Date:
          description: Date the payment is being made (YYYY-MM-DD) e.g. 2009-09-06
          type: string
          x-is-msdate: true
```

Here is what an API call give me today : 

```json
{
  date: 2024-09-24T00:00:00.000Z,
  // other properties
 }
```

Can you fix your backend to send plain date type or fix your OpenAPI schema please ?
